### ISSUE TITLE
11.2 greys-Java在线问题诊断工具

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/javaway#155]
greys是一个开源的github项目，用来分析运行中的java类、方法等信息。

greys工具地址：

https://github.com/oldmanpushcart/greys-anatomy/wiki/greys-pdf

**Comment by vieyahn2017** [comment]
### 先说下 jmap
之前有写 https://github.com/vieyahn2017/javaway/issues/102

jmap在容器内有局限性，可以采用
docker run --cap-add=SYS_PTRACE 

但是已经起好的容器，之前如果没有加权限，貌似很难处理。

```

./jmap -F -dump:live,format=b,file=heap1102.bin 27424
Attaching to process ID 27424, please wait...
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.execute(LinuxDebuggerLocal.java:163)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach(LinuxDebuggerLocal.java:278)
        at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
        at sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:611)
        at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:337)
        at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
        at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.HeapDumper.main(HeapDumper.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.tools.jmap.JMap.runTool(JMap.java:201)
        at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach0(Native Method)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.access$100(LinuxDebuggerLocal.java:62)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$1AttachTask.doit(LinuxDebuggerLocal.java:269)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.run(LinuxDebuggerLocal.java:138)



./jmap -F -dump:live,format=b,file=heap1102.bin 5168
Attaching to process ID 5168, please wait...
ERROR: ptrace(PTRACE_ATTACH, ..) failed for 5168: Operation not permitted
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process: ptrace(PTRACE_ATTACH, ..) failed for 5168: Operation not permitted
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process: ptrace(PTRACE_ATTACH, ..) failed for 5168: Operation not permitted
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.execute(LinuxDebuggerLocal.java:163)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach(LinuxDebuggerLocal.java:278)
        at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
        at sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:611)
        at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:337)
        at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
        at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.HeapDumper.main(HeapDumper.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.tools.jmap.JMap.runTool(JMap.java:201)
        at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process: ptrace(PTRACE_ATTACH, ..) failed for 5168: Operation not permitted
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach0(Native Method)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.access$100(LinuxDebuggerLocal.java:62)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$1AttachTask.doit(LinuxDebuggerLocal.java:269)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.run(LinuxDebuggerLocal.java:138)


```

**Comment by vieyahn2017** [comment]
## Greys工具使用

Greys工具主要可以用于jvm进程的异常诊断，对于无法断点调试的服务器，又要查看方法入参，执行耗时的情况，可以使用该工具来获得所需的信息。


1.将附件中Greys的六个文件上传至服务器某个包路径下，如/opt/greys，并赋予777的权限


2.切换到进程所属用户 su - uc_ims


3.执行./install-local.sh，安装Greys


4.使用ps -ef命令确认需要监控的进程ID编号




5.开始监控该进程： ./greys.sh 28679




6.监控进程之后，可以使用不同的命令打印需要的回显信息：

(1)watch命令可以看到方法的入参

watch -f *SpCorpResource search params[0] -x 1



-f的含义是在方法结束之后返回回显信息

*SpCorpResource 的含义是右匹配上述名称结尾的java类

search 是要监控的方法

params[0]是监控第一个入参

-x 1是指遍历输出第一个层级的参数


(2)trace用于监控方法执行时间

trace *SpCorpResource search




(3)tt命令用于循环监控方法执行总体情况

tt -t -n 3 *SpCorpResource search
-t表明希望记录下类*SpCorpResource 的search方法的每次执行情况。

-n 3参数指定你需要记录的次数





注：还有其他命令，可以参考官方文档：

https://yq.aliyun.com/articles/2390

**Comment by vieyahn2017** [comment]
我实践的，容器里使用报错

127.0.0.1:3658 -core /home/ivs_restful/.greys/lib/1.7.6.4/greys/greys-core.jar -agent /home/ivs_restful/.greys/lib/1.7.6.4/greys/greys-agent.jar4/greys/greys-core.jar -pid 59820 -target
start greys failed, because : com.sun.tools.attach.VirtualMachineDescriptor

就没咋研究了

**Comment by vieyahn2017** [comment]
cd greys
-rwxrwxrwx. 1 root root    1047 Nov  7  2016 ga.sh
-rwxrwxrwx. 1 root root   10595 Nov  7  2016 greys-agent.jar
-rwxrwxrwx. 1 root root 3472230 Nov  7  2016 greys-core.jar
-rwxrwxrwx. 1 root root    7972 Nov  7  2016 greys.sh
-rwxrwxrwx. 1 root root    2927 Nov  7  2016 gs.sh
-rwxrwxrwx. 1 root root     683 Nov  7  2016 install-local.sh
