### ISSUE TITLE
11.3 arthas-Java在线定位工具

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/javaway#156]
Arthas是阿里出品的在线定位工具，无需重启不改代码，即可监控JVM信息、打印方法参数、打印堆栈信息、线程状态、反编译class、动态替换class等，退出时会回退所有修改，定位问题神速，客户感知友好，功能强大，简单易用，官方文档非常友好，强烈推荐。

https://github.com/alibaba/arthas/blob/master/README_CN.md

**Comment by vieyahn2017** [comment]
### Java Attach API
https://blog.csdn.net/weixin_30827565/article/details/97664032


报这个错

```
java -jar arthas-boot.jar 51844
[INFO] arthas-boot version: 3.0.6-SNAPSHOT
[INFO] arthas home: /arthas
[INFO] Try to attach process 51844
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:73)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:100)
[ERROR] attach fail, targetPid: 51844

```

跟这个文件有关

jdk1.6.0_32/jre/lib/amd64/libattach.so
