### ISSUE TITLE
11.5 Spring框架中发送http请求--RestTemplate

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/javaway#50]
Spring框架中发送http请求--RestTemplate

**Comment by vieyahn2017** [comment]
Spring Boot(三)：RestTemplate提交表单数据的三种方法

2017年09月11日 23:13:13 蚁方阵 阅读数：30747 标签： RestTempla   提交表单数据  spring-boot payload 使用方法
个人分类： java
版权声明：本文为博主原创文章，未经博主允许不得转载。  https://blog.csdn.net/yiifaa/article/details/77939282
在REST接口的设计中，利用RestTemplate进行接口测试是种常见的方法，但在使用过程中，由于其方法参数众多，很多同学又混淆了表单提交与Payload提交方式的差别，而且接口设计与传统的浏览器使用的提交方式又有差异，经常出现各种各样的错误，如405错误，或者根本就得不到提交的数据，错误样例如下：

1. 用exchange方法提交

exchange既可以执行POST方法，还可以执行GET，所以应用最为广泛，使用方法如下：
```java
String url = "http://localhost/mirana-ee/app/login";
RestTemplate client = new RestTemplate();
HttpHeaders headers = new HttpHeaders();
//  请勿轻易改变此提交方式，大部分的情况下，提交方式都是表单提交
headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);
//  封装参数，千万不要替换为Map与HashMap，否则参数无法传递
MultiValueMap<String, String> params= new LinkedMultiValueMap<String, String>();
//  也支持中文
params.add("username", "用户名");
params.add("password", "123456");
HttpEntity<MultiValueMap<String, String>> requestEntity = new HttpEntity<MultiValueMap<String, String>>(params, headers);
//  执行HTTP请求
ResponseEntity<String> response = client.exchange(url, HttpMethod.POST, requestEntity, String.class);
//  输出结果
System.out.println(response.getBody());
```
2. 用postForEntity进行提交

postForEntity是对exchange的简化，仅仅只需要减少HttpMethod.POST参数，如下：
```java
//  上面的代码完全一样
//  仅需替换exchange方法
ResponseEntity<String> response = client.postForEntity(url, requestEntity , String.class );
```
3. 关于表单提交与Payload提交的差异

在Controller的方法参数中，如果将“@ModelAttribute”改为“@RequestBody”注解，则此时的提交方式为Payload方式提交，详细的差异请参见《 $.ajax使用总结(一)：Form提交与Payload提交》，代码示例如下：
```java
//  请注意@RequestBody注解
@RequestMapping(value="/login", method=RequestMethod.POST, consumes="application/json")
//  千万不要画蛇添足添加@ModelAttribute，否则会被其覆盖，如下
//  public Account getAccount(@RequestBody@ModelAttribute Account account)
public Account getAccount(@RequestBody Account account) {
    account.setVersion(new Date());
    return account;
}
```
再次强调一次，千万不要画蛇添足再次添加“@ModelAttribute”，因为其优先级比较高，所以系统会采用表单方式解析提交内容。

对于Payload方式，提交的内容一定要是String，且Header要设置为“application/json”，示例如下：
```java
//  请求地址
String url = "http://localhost/mirana-ee/app/login";
RestTemplate client = new RestTemplate();
//  一定要设置header
HttpHeaders headers = new HttpHeaders();
headers.setContentType(MediaType.APPLICATION_JSON_UTF8);
//  将提交的数据转换为String
//  最好通过bean注入的方式获取ObjectMapper
ObjectMapper mapper = new ObjectMapper();
Map<String, String> params= Maps.newHashMap();
params.put("username", "国米");
params.put("password", "123456");
String value = mapper.writeValueAsString(params);
HttpEntity<String> requestEntity = new HttpEntity<String>(value, headers);
//  执行HTTP请求
ResponseEntity<String> response = client.postForEntity(url, requestEntity , String.class );
System.out.println(response.getBody());
```
如果内容不是以String方式提交，那么一定会出现以下错误：
```
Exception in thread "main" org.springframework.web.client.HttpClientErrorException: 400 Bad Request
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:63)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
    at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:407)
```    
最后需要强调的是，通过@RequestBody是无法获取到请求参数，如将上面服务端的代码改为如下格式，则肯定得不到数据，但表单提交则相反。
```java
@RequestMapping(value="/login", consumes="application/json", method=RequestMethod.POST)
public Account getAccount(@RequestBody Account account, HttpServletRequest request) {
    //  肯定得不到参数值
    System.out.println(request.getParameter("username"));
    account.setVersion(new Date());
    return account;
}
```
4. HttpEntity的结构

HttpEntity是对HTTP请求的封装，包含两部分，header与body，header用于设置请求头，而body则用于设置请求体，所以其的构造器如下：
```java
//  value为请求体
//  header为请求头
HttpEntity<String> requestEntity = new HttpEntity<String>(value, headers);
```
5. HttpEntity与uriVariables

在RestTemplate的使用中，HttpEntity用于传递具体的参数值，而uriVariables则用于格式化Http地址，而不是地址参数，正确的用法如下：
```java
//  在地址中加入格式化参数path
String url = "http://localhost/mirana-ee/app/{path}";
//  准备格式化参数
Map<String, String> varParams = Maps.newHashMap();
varParams.put("path", "login");
//  其他代码略
//  格式化提交地址
ResponseEntity<String> response = client.postForEntity(url, requestEntity , String.class, varParams);
```
6. 关于HttpMessageConverter的说明

在网上的很多例子中，我发现很多人为了处理Payload提交，都添加了自定义的HttpMessageConverter，如下：
```java
//  完全没有必要
client.getMessageConverters().add(new MappingJackson2HttpMessageConverter());
client.getMessageConverters().add(new StringHttpMessageConverter());
```
然后，经过我查看源码与调试发现，RestTemplate内置了7种HttpMessageConverter，如下： 
1. org.springframework.http.converter.ByteArrayHttpMessageConverter 
2. org.springframework.http.converter.StringHttpMessageConverter 
3. org.springframework.http.converter.ResourceHttpMessageConverter 
4. org.springframework.http.converter.xml.SourceHttpMessageConverter 
5. org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter 
6. org.springframework.http.converter.xml.Jaxb2RootElementHttpMessageConverter 
7. org.springframework.http.converter.json.MappingJackson2HttpMessageConverter 

结论

RestTemplate能大幅简化了提交表单数据的难度，并且附带了自动转换JSON数据的功能，但只有理解了HttpEntity的组成结构（header与body），且理解了与uriVariables之间的差异，才能真正掌握其用法。

**Comment by vieyahn2017** [comment]
Spring RestTemplate中几种常见的请求方式

2017年09月11日 11:57:19 _江南一点雨 阅读数：76349 标签： spring
个人分类： java  JavaEE
所属专栏： Spring Cloud系列
版权声明：本文为sang原创文章，转载请注明出处。   https://blog.csdn.net/u012702547/article/details/77917939   
https://github.com/lenve/SimpleSpringCloud/tree/master/RestTemplate   在Spring Cloud中服务的发现与消费一文中，当我们从服务消费端去调用服务提供者的服务的时候，使用了一个很好用的对象，叫做RestTemplate，当时我们只使用了RestTemplate中最简单的一个功能getForEntity发起了一个get请求去调用服务端的数据，同时，我们还通过配置@LoadBalanced注解开启客户端负载均衡，RestTemplate的功能不可谓不强大，那么今天我们就来详细的看一下RestTemplate中几种常见请求方法的使用。  

### GET请求

在RestTemplate中，发送一个GET请求，我们可以通过如下两种方式：

第一种：getForEntity

getForEntity方法的返回值是一个ResponseEntity<T>，ResponseEntity<T>是Spring对HTTP请求响应的封装，包括了几个重要的元素，如响应码、contentType、contentLength、响应消息体等。比如下面一个例子：
```java
@RequestMapping("/gethello")
public String getHello() {
    ResponseEntity<String> responseEntity = restTemplate.getForEntity("http://HELLO-SERVICE/hello", String.class);
    String body = responseEntity.getBody();
    HttpStatus statusCode = responseEntity.getStatusCode();
    int statusCodeValue = responseEntity.getStatusCodeValue();
    HttpHeaders headers = responseEntity.getHeaders();
    StringBuffer result = new StringBuffer();
    result.append("responseEntity.getBody()：").append(body).append("<hr>")
            .append("responseEntity.getStatusCode()：").append(statusCode).append("<hr>")
            .append("responseEntity.getStatusCodeValue()：").append(statusCodeValue).append("<hr>")
            .append("responseEntity.getHeaders()：").append(headers).append("<hr>");
    return result.toString();
}
```
关于这段代码，我说如下几点：

getForEntity的第一个参数为我要调用的服务的地址，这里我调用了服务提供者提供的/hello接口，注意这里是通过服务名调用而不是服务地址，如果写成服务地址就没法实现客户端负载均衡了。
getForEntity第二个参数String.class表示我希望返回的body类型是String
拿到返回结果之后，将返回结果遍历打印出来
最终显示结果如下：

这里写图片描述

有时候我在调用服务提供者提供的接口时，可能需要传递参数，有两种不同的方式，如下：
```java
@RequestMapping("/sayhello")
public String sayHello() {
    ResponseEntity<String> responseEntity = restTemplate.getForEntity("http://HELLO-SERVICE/sayhello?name={1}", String.class, "张三");
    return responseEntity.getBody();
}
@RequestMapping("/sayhello2")
public String sayHello2() {
    Map<String, String> map = new HashMap<>();
    map.put("name", "李四");
    ResponseEntity<String> responseEntity = restTemplate.getForEntity("http://HELLO-SERVICE/sayhello?name={name}", String.class, map);
    return responseEntity.getBody();
}
```
可以用一个数字做占位符，最后是一个可变长度的参数，来一一替换前面的占位符
也可以前面使用name={name}这种形式，最后一个参数是一个map，map的key即为前边占位符的名字，map的value为参数值
第一个调用地址也可以是一个URI而不是字符串，这个时候我们构建一个URI即可，参数神马的都包含在URI中了，如下：
```java
@RequestMapping("/sayhello3")
public String sayHello3() {
    UriComponents uriComponents = UriComponentsBuilder.fromUriString("http://HELLO-SERVICE/sayhello?name={name}").build().expand("王五").encode();
    URI uri = uriComponents.toUri();
    ResponseEntity<String> responseEntity = restTemplate.getForEntity(uri, String.class);
    return responseEntity.getBody();
}
```
通过Spring中提供的UriComponents来构建Uri即可。

当然，服务提供者不仅可以返回String，也可以返回一个自定义类型的对象，比如我的服务提供者中有如下方法：
```java
@RequestMapping(value = "/getbook1", method = RequestMethod.GET)
public Book book1() {
    return new Book("三国演义", 90, "罗贯中", "花城出版社");
}
```
对于该方法我可以在服务消费者中通过如下方式来调用：
```java
@RequestMapping("/book1")
public Book book1() {
    ResponseEntity<Book> responseEntity = restTemplate.getForEntity("http://HELLO-SERVICE/getbook1", Book.class);
    return responseEntity.getBody();
}
```
运行结果如下：

这里写图片描述

第二种：getForObject

getForObject函数实际上是对getForEntity函数的进一步封装，如果你只关注返回的消息体的内容，对其他信息都不关注，此时可以使用getForObject，举一个简单的例子，如下：
```java
@RequestMapping("/book2")
public Book book2() {
    Book book = restTemplate.getForObject("http://HELLO-SERVICE/getbook1", Book.class);
    return book;
}
```
getForObject也有几个重载方法，如下：

这里写图片描述

这几个重载方法参数的含义和getForEntity一致，我就不再赘述了。

### POST请求

在RestTemplate中，POST请求可以通过如下三个方法来发起：

第一种：postForEntity

该方法和get请求中的getForEntity方法类似，如下例子：
```java
@RequestMapping("/book3")
public Book book3() {
    Book book = new Book();
    book.setName("红楼梦");
    ResponseEntity<Book> responseEntity = restTemplate.postForEntity("http://HELLO-SERVICE/getbook2", book, Book.class);
    return responseEntity.getBody();
}
```
方法的第一参数表示要调用的服务的地址
方法的第二个参数表示上传的参数
方法的第三个参数表示返回的消息体的数据类型
我这里创建了一个Book对象，这个Book对象只有name属性有值，将之传递到服务提供者那里去，服务提供者代码如下：
```java
@RequestMapping(value = "/getbook2", method = RequestMethod.POST)
public Book book2(@RequestBody Book book) {
    System.out.println(book.getName());
    book.setPrice(33);
    book.setAuthor("曹雪芹");
    book.setPublisher("人民文学出版社");
    return book;
}
```
服务提供者接收到服务消费者传来的参数book，给其他属性设置上值再返回，调用结果如下：

这里写图片描述

postForEntity的其他重载方法如下：

这里写图片描述

这些方法的参数含义和getForEntity参数的含义一致，不再赘述。

第二种：postForObject

如果你只关注，返回的消息体，可以直接使用postForObject。用法和getForObject一致。

第三种：postForLocation

postForLocation也是提交新资源，提交成功之后，返回新资源的URI，postForLocation的参数和前面两种的参数基本一致，只不过该方法的返回值为Uri，这个只需要服务提供者返回一个Uri即可，该Uri表示新资源的位置。

### PUT请求

在RestTemplate中，PUT请求可以通过put方法调用，put方法的参数和前面介绍的postForEntity方法的参数基本一致，只是put方法没有返回值而已。举一个简单的例子，如下：
```java
@RequestMapping("/put")
public void put() {
    Book book = new Book();
    book.setName("红楼梦");
    restTemplate.put("http://HELLO-SERVICE/getbook3/{1}", book, 99);
}
```
book对象是我要提交的参数，最后的99用来替换前面的占位符{1}

### DELETE请求

delete请求我们可以通过delete方法调用来实现，如下例子：
```java
@RequestMapping("/delete")
public void delete() {
    restTemplate.delete("http://HELLO-SERVICE/getbook4/{1}", 100);
}
```
delete方法也有几个重载的方法，不过重载的参数和前面基本一致，不赘述。

OK，以上就是我们对RestTemplate能够发送的请求的一个详细介绍，有问题欢迎留言讨论。

本文案例地址：https://github.com/lenve/SimpleSpringCloud/tree/master/RestTemplate

**Comment by vieyahn2017** [comment]
https://github.com/jiaoheng/mountain/blob/fa665e2099f4315d3b3aeb54c26d02107a2ad9c5/all/src/main/java/com/jiao/utils/http/HttpUtil.java


```java
package com.jiao.utils.http;

import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;

import com.jiao.utils.spring.SpringContextUtil;

public class HttpUtil {
	
	private static RestTemplate restTemplate = SpringContextUtil.getBean("restTemplate");
	
	public static <T> T sendGetRequest(String url, Class<T> returnType) throws Exception {
		return restTemplate.getForEntity(url, returnType).getBody();
	}
	
	public <T> T sendPostRequest(String url, Class<T> returnType, MultiValueMap<String, Object> params)
			throws Exception {
		HttpHeaders headers = new HttpHeaders();
		MediaType type = MediaType.parseMediaType("application/x-www-form-urlencoded; charset=UTF-8");
		headers.setContentType(type);
		HttpEntity<MultiValueMap<String, Object>> formEntity = new HttpEntity<MultiValueMap<String, Object>>(params,
				headers);
		return restTemplate.postForObject(url, formEntity, returnType);
	}
}
```

**Comment by vieyahn2017** [comment]
https://github.com/stenio2011/x-frame/blob/65e7a7786c4fe3b20e157268bae9b2a1db1a39a3/src/main/java/org/stenio/xframe/common/util/HttpUtil.java

```java
package org.stenio.xframe.common.util;

import org.apache.http.Header;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.stenio.xframe.common.exception.RuntimeXFrameException;
import org.stenio.xframe.common.http.HttpEntity;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by bjhexin3 on 2017/6/13.
 */
public class HttpUtil {


    private static final Logger logger = LoggerFactory.getLogger(HttpUtil.class);

    private static final CloseableHttpClient httpClient = HttpClients.createDefault();

    public static HttpEntity.ResponseEntity getForEntity(String url) {
        return getForEntity(url, null);
    }

    public static HttpEntity.ResponseEntity getForEntity(String url, Map<String, String> headers) {
        return getForEntity(url, headers, null);
    }

    public static HttpEntity.ResponseEntity getForEntity(String url, Map<String, String> headers, Map<String, Object> params) {
        HttpGet httpGet = new HttpGet();
        if (!CollectionUtils.isEmpty(headers)) {
            for (String headerName : headers.keySet()) {
                httpGet.setHeader(headerName, headers.get(headerName));
            }
        }

        URI uri = buildUrl(url, params);
        httpGet.setURI(uri);
        return invoke(httpGet);
    }

    public static  <T> T getForObject(String url, Class<T> responseType) {
        return getForObject(url, null, responseType);
    }

    public static <T> T getForObject(String url, Map<String, String> headers, Class<T> responseType) {
        return getForObject(url, headers, null, responseType);
    }

    public static <T> T getForObject(String url, Map<String, String> headers, Map<String, Object> params, Class<T> responseType) {
        HttpEntity.ResponseEntity responseEntity = getForEntity(url, headers, params);
        if (responseEntity.getStatusCode() == 200) {
            if (String.class.equals(responseType)) {
                return (T) responseEntity.getBody();
            }
            return JsonUtils.parse(responseEntity.getBody(), responseType);
        }
        logger.error("error status code, statusCode --> {}, url --> {}", responseEntity.getStatusCode(), url);
        return null;
    }

    private static URI buildUrl(String url, Map<String, Object> params) {
        try {
            URIBuilder uriBuilder = new URIBuilder(url);
            if (!CollectionUtils.isEmpty(params)) {
                for (String paramName : params.keySet()) {
                    Object valueObj = params.get(paramName);
                    if (!StringUtils.isEmpty(paramName) && valueObj != null) {
                        uriBuilder.setParameter(paramName, valueObj.toString());
                    }
                }
            }
            return uriBuilder.build();
        } catch (URISyntaxException e) {

            ExceptionUtils.logErrorAndThrow(logger, new RuntimeXFrameException("url syntax is error"), "url syntax is error, url : {}", url);
        }
        return null;
    }

    private static HttpEntity.ResponseEntity invoke(HttpUriRequest request) {
        HttpResponse httpResponse = sendRequest(request);
        HttpEntity.ResponseEntity responseEntity = parseResponse(httpResponse);
        return responseEntity;
    }

    private static HttpEntity.ResponseEntity parseResponse(HttpResponse httpResponse) {
        int statusCode = httpResponse.getStatusLine().getStatusCode();
        Map<String, String> headers = new HashMap<>();
        if (httpResponse.getAllHeaders() != null) {
            for (Header header : httpResponse.getAllHeaders()) {
                headers.put(header.getName(), header.getValue());
            }
        }
        String body = null;
        try {
            body = EntityUtils.toString(httpResponse.getEntity(), "UTF-8");
        } catch (IOException e) {
            ExceptionUtils.logErrorAndThrow(logger, new RuntimeXFrameException("exception occurs on parsing response to string."), "exception occurs on parsing response to string.");
        }
        return new HttpEntity.ResponseEntity(headers, body, statusCode);
    }

    private static HttpResponse sendRequest(HttpUriRequest request) {
        CloseableHttpResponse response = null;
        try {
            response = httpClient.execute(request);
        } catch (IOException e) {
            ExceptionUtils.logErrorAndThrow(logger, new RuntimeXFrameException("exception occurs on sending request."), "exception occurs on sending request.");
        }
        return response;
    }

}
```

**Comment by vieyahn2017** [comment]
这边有个https的例子

https://github.com/wyxiang/wxpay/blob/d5bc8a62319cf0e38258c3093915a823c0720291/src/main/java/com/wyx/wxpay/util/HttpUtil.java

```java
package com.wyx.wxpay.util;

import net.sf.json.JSONObject;
import org.codehaus.jackson.map.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;

import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocketFactory;
import javax.net.ssl.TrustManager;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.ConnectException;
import java.net.URL;
import java.util.Map;

//网络
public class HttpUtil {

	private static Logger log = LoggerFactory.getLogger(HttpUtil.class);

	//GET
	public static String get(String url) {
		return get(url, null);
	}

	//GET
	public static String get(String url, Map<String, String> params) {
		String pUrl = url;
		if (params != null) {
			pUrl = pUrl + "?";
			for(String key : params.keySet()) {
				if (!pUrl.endsWith("?")) {
					pUrl = pUrl + "&";
				}
				pUrl = pUrl + key + "=" + params.get(key);
			}
		}
		RestTemplate rest = new RestTemplate();
		return rest.getForObject(pUrl, String.class);
	}

	//POST
	public static String post(String url) {
		return post(url, null);
	}
	
	//POST
	public static String post(String url, Map<String, String> params) {
		MultiValueMap<String, String> bodyMap = new LinkedMultiValueMap<String, String>();
		if (params != null) {
			for(String key : params.keySet()) {
				bodyMap.set(key, params.get(key));
			}
		}
		RestTemplate rest = new RestTemplate();
		return rest.postForObject(url, bodyMap, String.class);
	}
	
	//GET for entity
	public static <T> T getForEntity(String url, Class<T> valueType) {
		return getForEntity(url, null, valueType);
	}
	
	//GET for entity
	public static <T> T getForEntity(String url, Map<String, String> params, Class<T> valueType) {
		try {
			ObjectMapper mapper = new ObjectMapper();
			return mapper.readValue(get(url, params), valueType);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}
	
	//POST for entity
	public static <T> T postForEntity(String url, Class<T> valueType) {
		return postForEntity(url, null, valueType);
	}
	
	//POST for entity
	public static <T> T postForEntity(String url, Map<String, String> params, Class<T> valueType) {
		try {
			ObjectMapper mapper = new ObjectMapper();
			return mapper.readValue(post(url, params), valueType);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}

	/**
	 * 发起https请求并获取结果
	 *
	 * @param requestUrl 请求地址
	 * @param requestMethod 请求方式（GET、POST）
	 * @param outputStr 提交的数据
	 * @return JSONObject(通过JSONObject.get(key)的方式获取json对象的属性值)
	 */
	public static JSONObject httpRequest(String requestUrl, String requestMethod, String outputStr) {
		JSONObject jsonObject = null;
		StringBuffer buffer = new StringBuffer();
		try {
			// 创建SSLContext对象，并使用我们指定的信任管理器初始化
			TrustManager[] tm = { new MyX509TrustManager() };
			SSLContext sslContext = SSLContext.getInstance("SSL", "SunJSSE");
			sslContext.init(null, tm, new java.security.SecureRandom());
			// 从上述SSLContext对象中得到SSLSocketFactory对象
			SSLSocketFactory ssf = sslContext.getSocketFactory();

			URL url = new URL(requestUrl);
			HttpsURLConnection httpUrlConn = (HttpsURLConnection) url.openConnection();
			httpUrlConn.setSSLSocketFactory(ssf);

			httpUrlConn.setDoOutput(true);
			httpUrlConn.setDoInput(true);
			httpUrlConn.setUseCaches(false);
			// 设置请求方式（GET/POST）
			httpUrlConn.setRequestMethod(requestMethod);

			if ("GET".equalsIgnoreCase(requestMethod))
				httpUrlConn.connect();

			// 当有数据需要提交时
			if (null != outputStr) {
				OutputStream outputStream = httpUrlConn.getOutputStream();
				// 注意编码格式，防止中文乱码
				outputStream.write(outputStr.getBytes("UTF-8"));
				outputStream.close();
			}

			// 将返回的输入流转换成字符串
			InputStream inputStream = httpUrlConn.getInputStream();
			InputStreamReader inputStreamReader = new InputStreamReader(inputStream, "utf-8");
			BufferedReader bufferedReader = new BufferedReader(inputStreamReader);

			String str = null;
			while ((str = bufferedReader.readLine()) != null) {
				buffer.append(str);
			}
			bufferedReader.close();
			inputStreamReader.close();
			// 释放资源
			inputStream.close();
			inputStream = null;
			httpUrlConn.disconnect();
			jsonObject = JSONObject.fromObject(buffer.toString());
		} catch (ConnectException ce) {
			log.error("Weixin server connection timed out.");
		} catch (Exception e) {
			log.error("https request error:{}", e);
		}
		return jsonObject;
	}

	public static String httpsRequest(String requestUrl, String requestMethod, String outputStr) {
		try {
			// 创建SSLContext对象，并使用我们指定的信任管理器初始化
			TrustManager[] tm = { new MyX509TrustManager() };
			SSLContext sslContext = SSLContext.getInstance("SSL", "SunJSSE");
			sslContext.init(null, tm, new java.security.SecureRandom());
			// 从上述SSLContext对象中得到SSLSocketFactory对象
			SSLSocketFactory ssf = sslContext.getSocketFactory();
			URL url = new URL(requestUrl);
			HttpsURLConnection conn = (HttpsURLConnection) url.openConnection();
			conn.setSSLSocketFactory(ssf);
			conn.setDoOutput(true);
			conn.setDoInput(true);
			conn.setUseCaches(false);
			// 设置请求方式（GET/POST）
			conn.setRequestMethod(requestMethod);
			conn.setRequestProperty("content-type", "application/x-www-form-urlencoded");
			// 当outputStr不为null时向输出流写数据
			if (null != outputStr) {
				OutputStream outputStream = conn.getOutputStream();
				// 注意编码格式
				outputStream.write(outputStr.getBytes("UTF-8"));
				outputStream.close();
			}
			// 从输入流读取返回内容
			InputStream inputStream = conn.getInputStream();
			InputStreamReader inputStreamReader = new InputStreamReader(inputStream, "utf-8");
			BufferedReader bufferedReader = new BufferedReader(inputStreamReader);
			String str = null;
			StringBuffer buffer = new StringBuffer();
			while ((str = bufferedReader.readLine()) != null) {
				buffer.append(str);
			}
			// 释放资源
			bufferedReader.close();
			inputStreamReader.close();
			inputStream.close();
			inputStream = null;
			conn.disconnect();
			return buffer.toString();
		} catch (ConnectException ce) {
			log.error("连接超时：{}", ce);
		} catch (Exception e) {
			log.error("https请求异常：{}", e);
		}
		return null;
	}

}
```
